print("----- Student Information -----")
Name=input("Enter Your Name: ")
Age=int(input("Enter Your Age: "))
Height=float(input("Enter Your Height: "))
Weight=float(input("Enter Your Weight: "))
City=input("Enter Your City: ")
Language=input("Enter Your Favourite Language: ")
print("===== Student Profile =====")
print("Name              :",Name)
print("Age               :",Age)
print("Height            :",Height)
print("Weight            :",Weight)
print("City              :",City)
print("Favourite Language:",Language)