print("Hello, GitHub!")
print("Today I started my Python practice.")
print("Hello, My Name is Shaikh Arsaslan and i want to become a Data Engineer")
Print("I am doing the course of big data cloud focused")
Print("And i also want to gather all that requirement certificates")
